/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  quietDocument: [
    {
      type: 'autogenerated',
      dirName: 'quiet/document',
    },
  ],
  quietPlugins: [
    {
      type: 'autogenerated',
      dirName: 'quiet/plugins',
    },
  ],
  solutionQuiet: [
    {
      type: 'autogenerated',
      dirName: 'solution/quiet'
    }
  ]
};

module.exports = sidebars;
